name: Run test case

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    run_test_case:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            otp:
              - vsn: "26.2.1-2"
                builder: "5.3-5:1.15.7-26.2.1-2-ubuntu24.04"
              - vsn: "27.2-1"
                builder: "5.4-3:1.17.3-27.2-1-ubuntu24.04"
    
        container:
          image: "ghcr.io/emqx/emqx-builder/${{ matrix.otp.builder }}"

        steps:
        - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

        - name: Install prerequisites
          run: |
            apt update
            apt install -y cmake

        - name: Run tests
          run: |
            make eunit
            make ct
            make cover

        - name: Coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
              make coveralls
        - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
          if: always()
          with:
            name: "logs-${{ matrix.otp.vsn }}"
            path: _build/test/logs
        - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
          with:
            name: "cover-${{ matrix.otp.vsn }}"
            path: _build/test/cover
